### ISSUE TITLE
Fatal Error on Wordpress site

### ISSUE THREAD

**Issue by apdvrjn** [archetyped/cornerstone#49]
I receive the following error when trying to update my Cornerstone plugin on Wordpress. Can someone help?

Fatal error: Uncaught Error: Call to undefined method ReflectionType::getName() in /data/18/3/42/59/3531385/user/3932531/htdocs/Home/wp-content/plugins/cornerstone/includes/classes/Plugin.php:106 Stack trace: #0 [internal function]: Themeco\Cornerstone\Plugin->Themeco\Cornerstone\{closure}(Object(ReflectionParameter)) #1 /data/18/3/42/59/3531385/user/3932531/htdocs/Home/wp-content/plugins/cornerstone/includes/classes/Plugin.php(117): array_map(Object(Closure), Array) #2 /data/18/3/42/59/3531385/user/3932531/htdocs/Home/wp-content/plugins/cornerstone/includes/classes/Plugin.php(137): Themeco\Cornerstone\Plugin->create('\\Themeco\\Corner...') #3 /data/18/3/42/59/3531385/user/3932531/htdocs/Home/wp-content/plugins/cornerstone/includes/classes/Plugin.php(73): Themeco\Cornerstone\Plugin->resolve('\\Themeco\\Corner...') #4 /data/18/3/42/59/3531385/user/3932531/htdocs/Home/wp-content/plugins/cornerstone/includes/classes/Plugin.php(44): Themeco\Cornerstone\Plugin->setup_services('is_admin') #5 /data/18/3/42/59/3531385/user/393253 in /data/18/3/42/59/3531385/user/3932531/htdocs/Home/wp-content/plugins/cornerstone/includes/classes/Plugin.php on line 106

**Comment by apdvrjn** [comment]
Might I request that Cornerstone be made compatible with Wordpress 5.7.1? Looks like that might be the issue.

**Comment by archetyped** [comment]
Hi, I'm not sure how you arrived at this forum, but this is the support forum for the [Cornerstone plugin in WordPress' official plugin directory](https://wordpress.org/support/plugin/cornerstone/).

It appears that you are using a different plugin that may be using the same name, as the error message you provided do not match this plugin's code. The plugin may have included support information on the plugin's own admin page.  You may also be able to find information on getting support via the site where you downloaded/purchased the plugin.

**Comment by okielokie** [comment]
thank you very much for your response archetyped. 

This is the plugin I'm using because it takes me to this page when I click on "view details" and "plugin homepage"
https://wordpress.org/plugins/cornerstone/

When I go to add new plugin and search for "cornerstone" only this plugin shows up: 
https://wordpress.org/plugins/cornerstone/

and this is the plugin that returns the error and doesn't let me activate it. 

How could there be a different plugin with the same name when there is only one plugin exist with this name? i also updated my wordpress version. 

This is details of the plugin when i click on it:


CornerstoneActivate \| Delete | The WordPress Page BuilderVersion 5.3.3 \| By Themeco \| View details
-- | --

Version: 0.7.8
Author: Archetyped
Last Updated: 4 months ago
Requires WordPress Version: 5.3 or higher
Compatible up to: 5.6.3
Active Installations: 100,000+

**Comment by archetyped** [comment]
Unfortunately, we do not have any control over the links another plugin developer uses.

We also have no control over the name a someone uses for a plugin _outside_ of WordPress' official plugin directory, which is where the plugin you are referring to appears to come from based on the information you provided.

Note that the plugin details from the plugin you have installed on your site say:

> The WordPress Page BuilderVersion 5.3.3 | By Themeco | View details

However, the Cornerstone plugin in WordPress' official plugin directory has completely different details (Author, Version, etc.):

> Version: 0.7.8
Author: Archetyped
Last Updated: 4 months ago
Requires WordPress Version: 5.3 or higher
Compatible up to: 5.6.3
Active Installations: 100,000+

As such, contacting the other plugin's developer (which appears to be **Themeco**) to get support on that plugin is recommended.
