### ISSUE TITLE
URL slug different on blog page and on post

### ISSUE THREAD

**Issue by balazimichal** [archetyped/cornerstone#5]
Hi There,

Thank you for doing such a wonderful job. It's really great plugin that I use all the time.

I am not sure if this is an issue or I do something wrong but previewing the blog page my URL looks like this:
http://someplace.com/nicholsons-intro/nicholsons-news-media/

And clicking on any post on this blog page my URL looks like this:
http://someplace.com/nicholsons-news-media/nicholsons-intro/sunt-in-culpa-qui-officia-deserunt/

The strange part is that the nicholsons-intro/nichoslons-news-media/ are the other way around on single post article while they should preserve the order as per the blog page.

Do you know why is this happening / how can I sort this out?

Many thanks,
Michal

**Comment by archetyped** [comment]
Hi, if I understand correctly... 

* `nicholsons-intro` and `nicholsons-news-media` are both **pages**
* `nicholsons-intro` is set as the **parent** of `nicholsons-news-media`
* `sunt-in-culpa-qui-officia-deserunt` is a **post**
* `nicholsons-intro` is set as the section for `sunt-in-culpa-qui-officia-deserunt`

Please let me know if this is correct.  Also please update your original message with the information requested on the following page so that I can fully evaluate your issue: [Reporting Issues](../wiki/Reporting-Issues).

Thanks.

**Comment by archetyped** [comment]
This ticket has been closed due to inactivity. If you are still experiencing an issue with Cornerstone, please provide the previously-requested details and I would be glad to reopen the ticket and take a look.
